### ISSUE TITLE
Texture node should be present when texture file cannot be found

### ISSUE THREAD

**Issue by ImagePlant** [jentron/Blender-PT2#35]
Summary:  When importing a prop/figure, all texture nodes should be created and linked even if the files they reference are missing

Here's how it stands now - when an imported prop/figure refers to a texture file that cannot be found:

![image](https://user-images.githubusercontent.com/57046940/88416597-53532300-cd95-11ea-89e5-976bd164e31d.png)

In such case that a texture file may not exist at the location specified, PT could create the nodes for those files and connect them (but leaving the file location blank). 

The user can then go into the Blender Shader and for each node missing a texture file, locate those files manually.

**Comment by jentron** [comment]
Great point
